// common.mjs — phần dùng chung của các emitter.

import fs from 'node:fs';
import path from 'node:path';
import { isAlwaysOn, emitPaths } from '../paths.mjs';
import { HUB } from '../assets.mjs';

/** Banner đánh dấu file generate — đặt NGAY SAU frontmatter đóng. */
export function banner(asset) {
  return `<!-- GENERATED BY 4AI — DO NOT EDIT.
     Source: ${asset.rel} (v${asset.version})
     Hub: ${HUB} · Regenerate: node tools/4ai.mjs sync -->`;
}

/** Banner cho file gộp nhiều asset. */
export function bannerAggregate(sourceNote) {
  return `<!-- GENERATED BY 4AI — DO NOT EDIT.
     ${sourceNote}
     Hub: ${HUB} · Regenerate: node tools/4ai.mjs sync -->`;
}

/** Dòng "Xem thêm" từ see-also. */
export function seeAlsoLine(asset) {
  const refs = asset['see-also'] ?? [];
  if (refs.length === 0) return '';
  return `\n\n> Xem thêm: ${refs.map((r) => `\`${r}\``).join(', ')}`;
}

// `[asset-id]` trong thân asset là cross-reference của corpus ("Nạp skill [pm-deadline-review]"),
// KHÔNG phải link markdown. Claude Code có Skill tool nên gọi theo tên là đủ — nó nạp được
// nguyên văn asset được tham chiếu. Cursor/Copilot/Antigravity KHÔNG có primitive tương đương:
// để nguyên text trần thì agent chỉ thấy một cái tên, không có đường nào tới nội dung, nên nó
// tự ứng biến từ phần tóm tắt trong command — đúng cái class lỗi "tự sinh script riêng thay vì
// gọi CLI bắt buộc". Đổi thành link tương đối trỏ đúng file đã sinh cho chính tool đó.
//
// Không đảm bảo agent sẽ đọc (không tool nào ngoài Claude Code cưỡng chế được) — chỉ bảo đảm
// đường dẫn tồn tại và đúng, thay vì bắt agent đoán.
const REF_PATTERN = /\[([a-z][a-z0-9-]*)\](?![([:])/g;

/**
 * Đổi cross-reference `[id]` thành link tương đối tới file mà `tool` sinh cho asset đó.
 * Chỉ đổi khi `id` THẬT SỰ là một asset trong corpus và asset đó ra file riêng (mode 'file')
 * — id lạ, hay asset bị inline vào file gộp, đều giữ nguyên text cũ.
 *
 * @param {string} body      thân asset
 * @param {object} p
 * @param {Array}  p.assets  toàn bộ asset đang emit (để phân giải id)
 * @param {string} p.tool    'cursor' | 'vscode' | 'antigravity' | 'claude'
 * @param {string} p.fromPath rel path của chính file đang sinh — gốc để tính đường tương đối
 * @param {object} [p.opts]  chuyển tiếp cho emitPaths (claudeRoot…)
 */
export function linkCrossRefs(body, { assets, tool, fromPath, opts = {} }) {
  const target = new Map();
  for (const a of assets) {
    const first = emitPaths(a, tool, opts)[0];
    if (first?.mode === 'file') target.set(a.id, first.path);
  }

  const fromDir = path.posix.dirname(fromPath.replace(/\\/g, '/'));
  return body.replace(REF_PATTERN, (whole, id) => {
    const dest = target.get(id);
    if (!dest) return whole;
    return `[${id}](${path.posix.relative(fromDir, dest.replace(/\\/g, '/'))})`;
  });
}

/**
 * Agent chỉ đọc — không có Edit/Write/NotebookEdit trong allowlist `tools`. Dùng để khai
 * `readonly: true` cho Cursor subagent (Cursor chỉ có cờ readonly thô, không có allowlist
 * theo từng tool như Claude Code) — chiếu lại đúng ý định đã khai ở `tools`, không phát
 * minh thêm field nguồn mới.
 */
const WRITE_TOOLS = ['Edit', 'Write', 'NotebookEdit'];
export function isReadonlyAgent(asset) {
  return asset.kind === 'agent' && Array.isArray(asset.tools)
    && !asset.tools.some((t) => WRITE_TOOLS.includes(t));
}

/** Sắp xếp asset ổn định: doctrine trước, rồi rule hard, luôn theo id. */
export function sortForAggregate(assets) {
  const rank = (a) => (a.kind === 'doctrine' ? 0 : a.severity === 'hard' ? 1 : 2);
  return assets.slice().sort((a, b) =>
    rank(a) !== rank(b) ? rank(a) - rank(b) : (a.id < b.id ? -1 : 1));
}

/** Các asset "luôn nạp" của một tập domain. */
export function alwaysOnAssets(assets) {
  return sortForAggregate(assets.filter(isAlwaysOn));
}

/** Các asset "theo yêu cầu". */
export function onDemandAssets(assets) {
  return assets.filter((a) => !isAlwaysOn(a));
}

// Cây runtime chép vào gói phân phối (Claude plugin, Cursor plugin — bất kỳ dialect nào đóng
// gói tự chứa). Giữ NGUYÊN đường dẫn tương đối so với hub: mcp/fbo/lib/tools.mjs import
// '../../../src/...' và src/database/*.mjs import '../../mcp/fbo/lib/...' — chép cùng layout
// thì mọi import còn đúng, không phải viết lại đường dẫn.
export const RUNTIME_DIRS = ['mcp/fbo', 'src', 'tools', 'data'];

// *.local.json là cấu hình per-máy, gitignore — không bao giờ đi kèm bản phân phối.
export const RUNTIME_EXCLUDE = /(^|\/)[^/]*\.local\.json$/;

/**
 * Đường dẫn tuyệt đối tới runtime (node.exe…) chỉ đúng trên máy sinh ra gói phân phối —
 * đổi thành tên lệnh trần để máy người cài tự phân giải qua PATH. Lệnh đã là tên trần thì
 * giữ nguyên. Dùng chung cho mọi dialect đóng gói (Claude plugin, Cursor plugin…).
 */
export function bareCommand(cmd) {
  const s = String(cmd ?? '').trim();
  if (!/[\\/]/.test(s)) return s;
  const ten = s.split(/[\\/]/).pop().replace(/\.exe$/i, '');
  return ten || s;
}

/** Liệt kê file runtime cần chép, đường dẫn tương đối so với hub, thứ tự ổn định. */
export function runtimeFiles() {
  const out = [];
  for (const dir of RUNTIME_DIRS) {
    const abs = path.join(HUB, dir);
    if (!fs.existsSync(abs)) continue;
    // node:fs.globSync không có `nodir` (đó là option của npm glob) — lọc thư mục bằng dirent.
    for (const d of fs.globSync('**/*', { cwd: abs, withFileTypes: true })) {
      if (!d.isFile()) continue;
      const sub = path.relative(abs, path.join(d.parentPath ?? d.path, d.name));
      const rel = `${dir}/${sub.replace(/\\/g, '/')}`;
      if (RUNTIME_EXCLUDE.test(rel)) continue;
      out.push(rel);
    }
  }
  return out.sort();
}
