import fs from 'node:fs';
import { execSync } from 'node:child_process';
const old = execSync('git show 4685e48:tools/lib/report.mjs', { encoding: 'utf8' });
const m = old.match(/export const CSS = `([\s\S]*?)`;/);
const css = fs.readFileSync('tools/templates/report/report.css', 'utf8');
console.log('equal to base', m[1] === css);
const iu = css.indexOf('.uin');
const ju = m[1].indexOf('.uin');
console.log('file .uin', JSON.stringify(css.slice(iu, iu + 220)));
console.log('base .uin', JSON.stringify(m[1].slice(ju, ju + 220)));
