// common.mjs — phần dùng chung của các emitter.

import { isAlwaysOn } from '../paths.mjs';
import { HUB } from '../assets.mjs';

/** Banner đánh dấu file generate — đặt NGAY SAU frontmatter đóng. */
export function banner(asset) {
  return `<!-- GENERATED BY 4AI — DO NOT EDIT.
     Source: ${asset.rel} (v${asset.version})
     Hub: ${HUB} · Regenerate: node tools/4ai.mjs sync -->`;
}

/** Banner cho file gộp nhiều asset. */
export function bannerAggregate(sourceNote) {
  return `<!-- GENERATED BY 4AI — DO NOT EDIT.
     ${sourceNote}
     Hub: ${HUB} · Regenerate: node tools/4ai.mjs sync -->`;
}

/** Dòng "Xem thêm" từ see-also. */
export function seeAlsoLine(asset) {
  const refs = asset['see-also'] ?? [];
  if (refs.length === 0) return '';
  return `\n\n> Xem thêm: ${refs.map((r) => `\`${r}\``).join(', ')}`;
}

/** Sắp xếp asset ổn định: doctrine trước, rồi rule hard, luôn theo id. */
export function sortForAggregate(assets) {
  const rank = (a) => (a.kind === 'doctrine' ? 0 : a.severity === 'hard' ? 1 : 2);
  return assets.slice().sort((a, b) =>
    rank(a) !== rank(b) ? rank(a) - rank(b) : (a.id < b.id ? -1 : 1));
}

/** Các asset "luôn nạp" của một tập domain. */
export function alwaysOnAssets(assets) {
  return sortForAggregate(assets.filter(isAlwaysOn));
}

/** Các asset "theo yêu cầu". */
export function onDemandAssets(assets) {
  return assets.filter((a) => !isAlwaysOn(a));
}
